name: aibirdie
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # image
  camera: ^0.5.8+1
  image_picker: ^0.6.6+4

  # audio
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1

  # networking
  http: ^0.12.1
  requests: ^3.1.0
  connectivity: ^0.4.8+6

  # backend
  # firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.0

  # file io
  path_provider: ^1.6.8
  path: ^1.6.4
  file_picker: ^1.9.0+1

  # animations
  flutter_animation_set: ^0.0.4
  flutter_staggered_animations: ^0.1.2
  modal_progress_hud: ^0.1.3

  # utilities
  share: ^0.6.4+2
  url_launcher: ^5.4.7
  timer_builder: ^1.3.0
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.8.1
  flutter_email_sender: ^3.0.1

  # os
  shared_preferences: ^0.5.7+2
  permission_handler: ^5.0.0+hotfix.6
  intl: ^0.16.1

  # API
  grpc: ^2.1.3
  protobuf: ^1.0.1



  # Old dependencies incase something goes wrong
  # image_picker: ^0.6.2+1
  # datetime_picker_formfield: ^0.4.3
  # geolocator: ^5.1.5
  # camera: ^0.5.7+4
  # path_provider: ^1.6.7
  # path: ^1.6.4
  # rflutter_alert: ^1.0.3
  # font_awesome_flutter: ^8.5.0
  # file_picker: ^1.4.3+2
  # flutter_audio_recorder: ^0.5.5
  # audioplayers: ^0.13.5
  # http: ^0.12.1
  # share: ^0.6.3+5
  # flutter_email_sender: ^2.2.2
  # url_launcher: ^5.4.1
  # flutter_animation_set: ^0.0.4
  # flutter_timer: ^0.0.6
  # modal_progress_hud: ^0.1.3
  # shared_preferences: ^0.5.7+2
  # permission_handler: ^5.0.0+hotfix.4
  # intl: ^0.15.8
  # timer_builder: ^1.3.0
  # google_sign_in: ^4.4.6
  # flutter_staggered_animations: ^0.1.2
  # requests: ^3.1.0
  # hardware_buttons: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: M_regular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: M_medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: M_thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: M_semi_bold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: OS_regular
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
    - family: OS_semi_bold
      fonts:
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
    - family: OS_bold
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
